import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children, params
}: {
  children: React.ReactNode,
  params: string
}) {
  return (
    <html lang={params}>
      <body >{children}</body>
    </html>
  )
}
